name: Build
on: 
    push: 
        branches: 
            - main
    pull_request: 
        branches: 
            - main

jobs: 
    gradle-build: 
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v5

            - uses: actions/setup-java@v5
              with: 
                  distribution: 'zulu'
                  java-version: '21'

            - name: Run Amper
              run: |
                curl -fsSL -o amper "https://packages.jetbrains.team/maven/p/amper/amper/org/jetbrains/amper/cli/0.6.0/cli-0.6.0-wrapper?download=true" && chmod +x amper
                ./amper build
