name: Build
on: 
    push: 
        branches: 
            - main
    pull_request: 
        branches: 
            - main

jobs: 
    gradle-build: 
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v4

            - uses: actions/setup-java@v4
              with: 
                  distribution: 'zulu'
                  java-version: '21'

            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@v4

            - name: Setup Amper
              run: |
                curl -s https://packages.jetbrains.team/maven/p/amper/amper/org/jetbrains/amper/amper-cli/0.6.0/amper-cli-0.6.0.zip -o amper-cli.zip
                unzip -q amper-cli.zip
                chmod +x amper-cli-0.6.0/bin/amper
                ./amper-cli-0.6.0/bin/amper init

            - name: Gradle Build
              run: ./gradlew build
